idl.cmake: add missing omniidl flag
This solves the following error:

error: no match for ‘operator<<=’ (operand types are ‘CORBA::Any’ and ‘...’)

Followed by thousands of no known conversion for argument 1 from ‘...’ to ‘cdrStream&’